/* ====================================================================
   1. TẠO MATERIALIZED VIEWS (Kéo dữ liệu từ phân mảnh khác)
==================================================================== */
-- YÊU CẦU: Tại server đích (GiamDoc31Link), các bảng gốc đã phải được tạo MATERIALIZED VIEW LOG.
CREATE MATERIALIZED VIEW DANH_MUC 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.DANH_MUC@link_to_cn1;

CREATE MATERIALIZED VIEW NHA_XUAT_BAN 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.NHA_XUAT_BAN@link_to_cn1;

CREATE MATERIALIZED VIEW TAC_GIA 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.TAC_GIA@link_to_cn1;

CREATE MATERIALIZED VIEW SACH_VPP 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.SACH_VPP@link_to_cn1;

CREATE MATERIALIZED VIEW CHI_NHANH 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.CHI_NHANH@link_to_cn1;

CREATE MATERIALIZED VIEW KHACH_HANG 
REFRESH FAST ON DEMAND WITH PRIMARY KEY AS SELECT * FROM CN1.KHACH_HANG@link_to_cn1;

drop materialized view DANH_MUC;
drop materialized view NHA_XUAT_BAN;
drop materialized view TAC_GIA;
drop materialized view SACH_VPP;
drop materialized view CHI_NHANH;
drop materialized view KHACH_HANG;
/* ====================================================================
   2. TẠO BẢNG CỤC BỘ (LOCAL TABLES)
==================================================================== */
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR2(20) PRIMARY KEY,
    TenNV NVARCHAR2(100),
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    SDT VARCHAR2(20),
    DiaChi NVARCHAR2(255),
    MaCN VARCHAR2(20),
    ChucVu NVARCHAR2(50),
    NgayVaoLam DATE,
    Luong NUMBER
);

CREATE TABLE KHO_HANG (
    MaSP VARCHAR2(20),
    MaCN VARCHAR2(20),
    SoLuongTon NUMBER,
    PRIMARY KEY (MaSP, MaCN)
);

CREATE TABLE HOA_DON (
    MaHD VARCHAR2(30) PRIMARY KEY,
    MaKH VARCHAR2(30),
    MaNV VARCHAR2(20),
    MaCN VARCHAR2(20),
    NgayLap DATE,
    TongTien NUMBER
);

CREATE TABLE CHI_TIET_HOA_DON (
    MaHD VARCHAR2(30),
    MaSP VARCHAR2(20),
    SoLuong NUMBER,
    DonGia NUMBER,
    ThanhTien NUMBER,
    PRIMARY KEY (MaHD, MaSP)
);


/* ====================================================================
   3. RÀNG BUỘC KHÓA NGOẠI (FOREIGN KEYS)
==================================================================== */
-- Ràng buộc với các Materialized Views
ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_DM FOREIGN KEY (MaDM) REFERENCES DANH_MUC(MaDM);
ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_NXB FOREIGN KEY (MaNXB) REFERENCES NHA_XUAT_BAN(MaNXB);
ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_TG FOREIGN KEY (MaTG) REFERENCES TAC_GIA(MaTG);

-- Ràng buộc với các bảng và MV
ALTER TABLE NHAN_VIEN ADD CONSTRAINT FK_NV_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE KHO_HANG ADD CONSTRAINT FK_KHO_SP FOREIGN KEY (MaSP) REFERENCES SACH_VPP(MaSP);
ALTER TABLE KHO_HANG ADD CONSTRAINT FK_KHO_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE CHI_TIET_HOA_DON ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD);
ALTER TABLE CHI_TIET_HOA_DON ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP) REFERENCES SACH_VPP(MaSP);

COMMIT;

select * from DANH_MUC;
select * from NHA_XUAT_BAN;
select * from TAC_GIA;
select * from SACH_VPP;
select * from CHI_NHANH;
select * from KHACH_HANG;

EXEC DBMS_MVIEW.REFRESH('SACH_VPP');