-- 1.	Non-Repeatable Read
-- 1.2.	Minh họa vấn đề
-- t0 - cn1 -- QuanLyKho
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;
-- t0 - cn2 -- NhanVien
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

-- t1 - cn2
SELECT GiaBan FROM CN1.SACH_VPP@NhanVien21Link WHERE MaSP = 'SP0001';

--t2 - cn1
UPDATE CN1.SACH_VPP SET GiaBan = 300000 WHERE MaSP = 'SP0001';

--t3 - cn1
COMMIT;

--t4 - cn2
SELECT GiaBan FROM CN1.SACH_VPP@NhanVien21Link WHERE MaSP = 'SP0001';

-- 1.3.	Giải quyết
-- t0 - cn1 
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;
-- t0 - cn2
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE;

-- t1 - cn2
SELECT GiaBan FROM CN1.SACH_VPP@NhanVien21Link WHERE MaSP = 'SP0001';

-- t2 - cn1
UPDATE CN1.SACH_VPP SET GiaBan = 240000 WHERE MaSP = 'SP0001';

-- t3 - cn1
COMMIT;

-- t4 - cn2
SELECT GiaBan FROM CN1.SACH_VPP@NhanVien21Link WHERE MaSP = 'SP0001';

-- t5 - cn2
COMMIT;

-- t6 - cn2
SELECT GiaBan FROM CN1.SACH_VPP@NhanVien21Link WHERE MaSP = 'SP0001';

-- 2.	Phantom Read
-- 2.2.	Minh họa vấn đề
-- t0 - cn1 -- GiamDoc
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;
-- t0 - cn3 -- NhanVien
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

-- t1 - cn1
-- Chạy tại máy CN1 (User GiamDoc)
SELECT COUNT(*) FROM (
SELECT MaSP, SoLuongTon FROM CN1.KHO_HANG UNION ALL
SELECT MaSP, SoLuongTon FROM CN2.KHO_HANG@GiamDoc12Link UNION ALL
SELECT MaSP, SoLuongTon FROM CN3.KHO_HANG@GiamDoc13Link)
WHERE SoLuongTon = 100;

-- t2 - cn3
INSERT INTO CN3.KHO_HANG (MaSP, MaCN, SoLuongTon) VALUES ('SP0700', 'CN03', 100);

-- t3 - cn3
COMMIT;

-- t4 - cn1
SELECT COUNT(*) FROM (
SELECT MaSP, SoLuongTon FROM CN1.KHO_HANG UNION ALL
SELECT MaSP, SoLuongTon FROM CN2.KHO_HANG@GiamDoc12Link UNION ALL
SELECT MaSP, SoLuongTon FROM CN3.KHO_HANG@GiamDoc13Link)
WHERE SoLuongTon = 100;

-- 2.3.	Cách giải quyết
-- t0 - cn1
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE; 
-- t0 - cn3
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE; 

-- t1 - cn1
SELECT COUNT(*) FROM (
SELECT MaSP, SoLuongTon FROM CN1.KHO_HANG UNION ALL
SELECT MaSP, SoLuongTon FROM CN2.KHO_HANG@GiamDoc12Link UNION ALL
SELECT MaSP, SoLuongTon FROM CN3.KHO_HANG@GiamDoc13Link)
WHERE SoLuongTon = 100;

-- t2 - cn3
INSERT INTO CN3.KHO_HANG (MaSP, MaCN, SoLuongTon) VALUES ('SP0700', 'CN03', 100);

-- t3 - cn3
COMMIT;

-- t4 - cn1
SELECT COUNT(*) FROM (
SELECT MaSP, SoLuongTon FROM CN1.KHO_HANG UNION ALL
SELECT MaSP, SoLuongTon FROM CN2.KHO_HANG@GiamDoc12Link UNION ALL
SELECT MaSP, SoLuongTon FROM CN3.KHO_HANG@GiamDoc13Link)
WHERE SoLuongTon = 100;


-- t5 - cn1
COMMIT;

-- t6 - cn1
SELECT COUNT(*) FROM (
SELECT MaSP, SoLuongTon FROM CN1.KHO_HANG UNION ALL
SELECT MaSP, SoLuongTon FROM CN2.KHO_HANG@GiamDoc12Link UNION ALL
SELECT MaSP, SoLuongTon FROM CN3.KHO_HANG@GiamDoc13Link)
WHERE SoLuongTon = 100;


-- 3.	Lost Update
-- 3.2.	Minh họa vấn đề
-- t0 - cn1 -- QLKho
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;
-- t0 - cn2 -- QLKho
ALTER SESSION SET ISOLATION_LEVEL = READ COMMITTED;

-- t1 - cn1
SELECT GiaBan FROM CN1.SACH_VPP WHERE MaSP = 'SP0009';

-- t2 - cn1
UPDATE CN1.SACH_VPP SET GiaBan = 200000 WHERE MaSP = 'SP0009';

-- t3 - cn2
UPDATE CN1.SACH_VPP@QuanLyKho21Link SET GiaBan = 240000 WHERE MaSP = 'SP0009';

--t4 - cn1
COMMIT;

-- t5 - cn2
COMMIT;

-- t6 - cn1
SELECT GiaBan FROM CN1.SACH_VPP WHERE MaSP = 'SP0009';

-- 3.3.	Cách giải quyết
-- t0 - cn1
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE; 
-- t0 - cn2
ALTER SESSION SET ISOLATION_LEVEL = SERIALIZABLE; 

-- t1 - cn1
SELECT GiaBan FROM CN1.SACH_VPP WHERE MaSP = 'SP0009';

-- t2 - cn1
UPDATE CN1.SACH_VPP SET GiaBan = 300000 WHERE MaSP = 'SP0009';

-- t3 - cn2
UPDATE CN1.SACH_VPP@QuanLyKho21Link SET GiaBan = 270000 WHERE MaSP = 'SP0009';

-- t4 - cn1
COMMIT;

-- t5 - cn2
COMMIT;

-- t6 - cn1
SELECT GiaBan FROM CN1.SACH_VPP WHERE MaSP = 'SP0009';


SELECT * FROM CN1.KHO_HANG
WHERE MASP = 'SP0444';

SELECT * FROM CN3.KHO_HANG@QuanLyKho13Link
WHERE MASP = 'SP0444';

-- 4.	Deadlock
-- 4.2.	Minh họa vấn đề 
-- t1 - cn2 -- QLKho
UPDATE CN1.KHO_HANG SET SoLuongTon = SoLuongTon + 10 WHERE MaSP = 'SP0444';

-- t2 - cn3 -- QlKho
UPDATE CN3.KHO_HANG SET SoLuongTon = SoLuongTon + 20 WHERE MaSP = 'SP0444';

-- t3 - cn2
UPDATE CN3.KHO_HANG@QuanLyKho13Link SET SoLuongTon = SoLuongTon - 10 WHERE MaSP = 'SP0444';

-- t4 - cn3
UPDATE CN3.KHO_HANG@QuanLyKho32Link SET SoLuongTon = SoLuongTon - 20 WHERE MaSP = 'SP0444';












