
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- 1.1 Tạo các tài khoản
CREATE USER GiamDoc IDENTIFIED BY giamdoc;
CREATE USER QuanLyKho IDENTIFIED BY qlkho;
CREATE USER NhanVien IDENTIFIED BY nhanvien;
CREATE USER QuanLyKhoVirtual IDENTIFIED BY qlkhov;
CREATE USER NhanVienVirtual IDENTIFIED BY nhanvienv;

-- 1.2 Cấp quyền cho GiamDoc (Trùm cuối tại máy 1)
GRANT CONNECT, RESOURCE TO GiamDoc;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.NHAN_VIEN TO GiamDoc;
GRANT SELECT ON CN1.CHI_NHANH TO GiamDoc;
GRANT SELECT ON CN1.KHACH_HANG TO GiamDoc;
GRANT SELECT ON CN1.SACH_VPP TO GiamDoc;
GRANT SELECT ON CN1.DANH_MUC TO GiamDoc;
GRANT SELECT ON CN1.HOA_DON TO GiamDoc;
GRANT SELECT ON CN1.CHI_TIET_HOA_DON TO GiamDoc;
GRANT SELECT ON CN1.KHO_HANG TO GiamDoc;

-- 1.3 Cấp quyền cho QuanLyKho (Chỉ tại máy 1)
GRANT CONNECT TO QuanLyKho;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.SACH_VPP TO QuanLyKho;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.DANH_MUC TO QuanLyKho;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.KHO_HANG TO QuanLyKho;
GRANT SELECT ON CN1.NHA_XUAT_BAN TO QuanLyKho;
GRANT SELECT ON CN1.CHI_TIET_HOA_DON TO QuanLyKho;

-- 1.4 Cấp quyền cho NhanVien (Bán hàng tại máy 1)  
GRANT CONNECT TO NhanVien;
GRANT SELECT, INSERT, UPDATE ON CN1.KHACH_HANG TO NhanVien;
GRANT SELECT ON CN1.SACH_VPP TO NhanVien;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.HOA_DON TO NhanVien;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.CHI_TIET_HOA_DON TO NhanVien;

-- 1.5 Cấp quyền cho các tài khoản Virtual (Để chi nhánh 2, 3 kết nối vào)
GRANT CONNECT TO QuanLyKhoVirtual;
GRANT SELECT,UPDATE ON CN1.KHO_HANG TO QuanLyKhoVirtual;
GRANT SELECT, UPDATE ON CN1.SACH_VPP TO QuanLyKhoVirtual;

GRANT CONNECT TO NhanVienVirtual;
GRANT SELECT ON CN1.HOA_DON TO NhanVienVirtual;
GRANT SELECT,INSERT, DELETE, UPDATE ON CN1.CHI_TIET_HOA_DON TO NhanVienVirtual;
GRANT SELECT ON CN1.SACH_VPP TO NhanVienVirtual;
GRANT SELECT, INSERT, UPDATE, DELETE ON CN1.KHACH_HANG TO NhanVienVirtual;

-- 1.6 Tạo Database Links từ máy 1 đi máy 2 và 3
CREATE PUBLIC DATABASE LINK GiamDoc12Link CONNECT TO GiamDocVirtual IDENTIFIED BY giamdocv USING 'CN2_LINK';
CREATE PUBLIC DATABASE LINK GiamDoc13Link CONNECT TO GiamDocVirtual IDENTIFIED BY giamdocv USING 'CN3_LINK';
CREATE PUBLIC DATABASE LINK QuanLyKho12Link CONNECT TO QuanLyKhoVirtual IDENTIFIED BY qlkhov USING 'CN2_LINK';
CREATE PUBLIC DATABASE LINK QuanLyKho13Link CONNECT TO QuanLyKhoVirtual IDENTIFIED BY qlkhov USING 'CN3_LINK';
CREATE PUBLIC DATABASE LINK NhanVien12Link CONNECT TO NhanVienVirtual IDENTIFIED BY nhanvienv USING 'CN2_LINK';
CREATE PUBLIC DATABASE LINK NhanVien13Link CONNECT TO NhanVienVirtual IDENTIFIED BY nhanvienv USING 'CN3_LINK';

select count(*) from hoa_don


