-- NHÓM 1: DANH MỤC
CREATE TABLE DANH_MUC (
    MaDM VARCHAR2(20) PRIMARY KEY,
    TenDM NVARCHAR2(100),
    MoTa NVARCHAR2(255)
);

CREATE TABLE NHA_XUAT_BAN (
    MaNXB VARCHAR2(20) PRIMARY KEY,
    TenNXB NVARCHAR2(100),
    DiaChi NVARCHAR2(255),
    SoDienThoai VARCHAR2(20)
);

CREATE TABLE TAC_GIA (
    MaTG VARCHAR2(20) PRIMARY KEY,
    TenTG NVARCHAR2(100),
    QuocTich NVARCHAR2(50),
    TieuSu NVARCHAR2(500)
);

CREATE TABLE SACH_VPP (
    MaSP VARCHAR2(20) PRIMARY KEY,
    TenSP NVARCHAR2(255),
    MaDM VARCHAR2(20),
    MaNXB VARCHAR2(20),
    MaTG VARCHAR2(20),
    GiaBan NUMBER,
    DonViTinh NVARCHAR2(50)
);

-- NHÓM 2: TỔ CHỨC & NHÂN SỰ
CREATE TABLE CHI_NHANH (
    MaCN VARCHAR2(20) PRIMARY KEY,
    TenCN NVARCHAR2(100),
    KhuVuc NVARCHAR2(50),
    DiaChi NVARCHAR2(255)
);

CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR2(20) PRIMARY KEY,
    TenNV NVARCHAR2(100),
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    SDT VARCHAR2(20),
    DiaChi NVARCHAR2(255),
    MaCN VARCHAR2(20),
    ChucVu NVARCHAR2(50),
    NgayVaoLam DATE,
    Luong NUMBER
);

-- NHÓM 3: KHÁCH HÀNG & KHO
CREATE TABLE KHACH_HANG (
    MaKH VARCHAR2(30) PRIMARY KEY,
    TenKH NVARCHAR2(100),
    SoDienThoai VARCHAR2(20),
    Email VARCHAR2(100),
    DiaChi NVARCHAR2(255),
    GioiTinh NVARCHAR2(10),
    NgaySinh DATE,
    DiemTichLuy NUMBER
);

CREATE TABLE KHO_HANG (
    MaSP VARCHAR2(20),
    MaCN VARCHAR2(20),
    SoLuongTon NUMBER,
    PRIMARY KEY (MaSP, MaCN)
);

-- NHÓM 4: GIAO DỊCH
CREATE TABLE HOA_DON (
    MaHD VARCHAR2(30) PRIMARY KEY,
    MaKH VARCHAR2(30),
    MaNV VARCHAR2(20),
    MaCN VARCHAR2(20),
    NgayLap DATE,
    TongTien NUMBER
);

CREATE TABLE CHI_TIET_HOA_DON (
    MaHD VARCHAR2(30),
    MaSP VARCHAR2(20),
    SoLuong NUMBER,
    DonGia NUMBER,
    ThanhTien NUMBER,
    PRIMARY KEY (MaHD, MaSP)
);


ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_DM FOREIGN KEY (MaDM) REFERENCES DANH_MUC(MaDM);
ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_NXB FOREIGN KEY (MaNXB) REFERENCES NHA_XUAT_BAN(MaNXB);
ALTER TABLE SACH_VPP ADD CONSTRAINT FK_SACH_TG FOREIGN KEY (MaTG) REFERENCES TAC_GIA(MaTG);
ALTER TABLE NHAN_VIEN ADD CONSTRAINT FK_NV_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE KHO_HANG ADD CONSTRAINT FK_KHO_SP FOREIGN KEY (MaSP) REFERENCES SACH_VPP(MaSP);
ALTER TABLE KHO_HANG ADD CONSTRAINT FK_KHO_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_CN FOREIGN KEY (MaCN) REFERENCES CHI_NHANH(MaCN);
ALTER TABLE CHI_TIET_HOA_DON ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD);
ALTER TABLE CHI_TIET_HOA_DON ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP) REFERENCES SACH_VPP(MaSP);

-- Chạy với tư cách user BTL1 hoặc người sở hữu bảng
CREATE MATERIALIZED VIEW LOG ON DANH_MUC WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON NHA_XUAT_BAN WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON TAC_GIA WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON SACH_VPP WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON KHACH_HANG WITH PRIMARY KEY;
CREATE MATERIALIZED VIEW LOG ON CHI_NHANH WITH PRIMARY KEY;




-- 1. Xóa nhóm Giao dịch & Chi tiết (Vì chúng phụ thuộc vào hầu hết các bảng khác)
DROP TABLE CHI_TIET_HOA_DON;
DROP TABLE HOA_DON;
DROP TABLE KHO_HANG;
DROP TABLE PHIEU_NHAP;

-- 2. Xóa các bảng có chứa khóa ngoại trung gian
DROP TABLE SACH_VPP;
DROP TABLE NHAN_VIEN;

-- 3. Xóa các bảng danh mục gốc (Bảng Cha)
DROP TABLE KHACH_HANG;
DROP TABLE CHI_NHANH;
DROP TABLE DANH_MUC;
DROP TABLE NHA_XUAT_BAN;
DROP TABLE TAC_GIA;

COMMIT;